const revealEls = document.querySelectorAll('.reveal'); const revealObserver = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('visible'); revealObserver.unobserve(entry.target) } }), { threshold: .12 }); revealEls.forEach(el => revealObserver.observe(el));
const menuBtn = document.getElementById('menuBtn'), nav = document.getElementById('nav'); if (menuBtn && nav) { menuBtn.addEventListener('click', () => nav.classList.toggle('open')); nav.querySelectorAll('a').forEach(link => link.addEventListener('click', () => nav.classList.remove('open'))) }
const sections = document.querySelectorAll('main section[id]'), navLinks = document.querySelectorAll('.nav a'); addEventListener('scroll', () => { let current = ''; sections.forEach(sec => { if (scrollY >= sec.offsetTop - 140) current = sec.id }); navLinks.forEach(link => link.classList.toggle('active', link.getAttribute('href') === `#${current}`)) });
const projects = {
    "create-portfolio-blog-website": { title: "Create Portfolio", category: "هوية رقمية", description: "تجربة رقمية احترافية لعرض الهوية والخدمات والأعمال بشكل واضح يعكس قوة العلامة التجارية." },
    "snefro-factory-ecommerce": { title: "Enterprise E-Commerce Engine (Snefro Factory Stack)", category: "تجارة إلكترونية", description: "منصة تجارة إلكترونية قابلة للتوسع لإدارة المنتجات وتجربة العملاء والطلبات ودعم نمو النشاط التجاري." },
    "factory-his": { title: "Factory Operations Management System", category: "نظام إدارة عمليات", description: "نظام مخصص لتنظيم بيانات المؤسسة وسير العمل ومتابعة العمليات من مكان واحد." },
    "hospital-system": { title: "Integrated Hospital Management System", category: "تقنية الرعاية الصحية", description: "منصة متكاملة لدعم عمليات المستشفى والبيانات الإدارية ومسارات العمل الطبية." },
    "appnabra-education-platform": { title: "Secure Digital Academy & Content Protection Platform", category: "منصة تعليمية", description: "منظومة تعليم رقمي لإدارة الدورات والمتعلمين والمحتوى المحمي والعمليات التعليمية." },
    "neo-gym-system": { title: "Fitness Club Management Suite", category: "إدارة الأعمال", description: "نظام لإدارة الاشتراكات والعملاء والحضور والخدمات والعمليات اليومية للنوادي الرياضية." },
    "neo-pos-system": { title: "Retail POS & Sales Intelligence System", category: "نقاط البيع", description: "نظام لإدارة المبيعات والمنتجات والفواتير والحركة اليومية والتقارير بشكل منظم." },
    "nile-noir-hotel": { title: "Luxury Hospitality Management System", category: "الضيافة والفنادق", description: "تجربة رقمية راقية لعرض الفندق والخدمات وتسهيل وصول الضيوف للمعلومات المطلوبة." },
    "pro-pre-idea-crm": { title: "Advanced Enterprise CRM وإدارة العمليات Suite", category: "CRM وإدارة العمليات", description: "بيئة مركزية لإدارة بيانات العملاء والفرص والمهام ومتابعة سير العمل التجاري." },
    "snefro-clothing-store": { title: "Enterprise E-Commerce Engine (Snefro Factory Stack)", category: "متجر أزياء", description: "تجربة تسوق حديثة ومتجاوبة لعرض المنتجات والتصنيفات وتسهيل رحلة العميل." },
    "tawqit-education-redesign": { title: "Educational Architecture Redesign Suite", category: "إعادة تصميم منصة تعليمية", description: "إعادة تصميم استراتيجية لتحسين التنقل وتنظيم المحتوى وتقديم تجربة تعليمية أكثر احترافية." },
    "theqa": { title: "Theqa Digital Services Platform", category: "منصة خدمات", description: "منصة رقمية منظمة تربط المستخدمين بالخدمات من خلال رحلة واضحة وسهلة الاستخدام." },
    "theqa-services-website": { title: "Theqa Corporate Services Experience", category: "موقع خدمات", description: "موقع احترافي يوضح الخدمات والقيمة المقدمة ويساعد على تحويل الزائر إلى عميل." },
    "viver-website": { title: "Viver Premium Web Experience", category: "تجربة رقمية", description: "موقع حديث ومتجاوب بهوية مرنة لعرض المحتوى والخدمات بصورة احترافية." },
    "social": { title: "Social Engagement Platform", category: "منصة اجتماعية", description: "منتج اجتماعي قابل للتوسع يركز على اكتشاف المحتوى والتفاعل وسهولة الاستخدام." }
};
const order = ["snefro-clothing-store", "tawqit-education-redesign", "theqa", "create-portfolio-blog-website", "snefro-factory-ecommerce", "factory-his", "hospital-system", "appnabra-education-platform", "nile-noir-hotel", "neo-gym-system", "neo-pos-system", "pro-pre-idea-crm", "theqa-services-website", "viver-website", "social"];
const grid = document.getElementById('projectsGrid'); if (grid) grid.innerHTML = order.map((slug, i) => { const p = projects[slug]; return `<article class="project-card reveal visible" data-project="${slug}" tabindex="0"><div class="project-cover"><img src="assets/projects/${slug}/cover.PNG" alt="${p.title}" loading="lazy" onerror="this.style.display='none'"><span class="project-index">${String(i + 1).padStart(2, '0')}</span></div><div class="project-content"><span class="project-category">${p.category}</span><h3>${p.title}</h3><p>${p.description}</p><span class="project-link">عرض المشروع <i class="bi bi-arrow-up-right"></i></span></div></article>` }).join('');
const eventsTrack = document.getElementById('eventsTrack'); if (eventsTrack) eventsTrack.innerHTML = Array.from({ length: 6 }, (_, i) => `<article class="event-card"><img src="assets/events/${i + 1}.png" alt="فعالية MousaTech رقم ${i + 1}" loading="lazy" onerror="this.closest('.event-card').style.display='none'"><div><b>ندوات وفعاليات واجتماعات MousaTech التقنية</b><small>فعالية ${String(i + 1).padStart(2, '0')}</small></div></article>`).join('');
const modal = document.getElementById('projectModal'), modalContent = document.getElementById('projectModalContent'); function openProject(slug) { const p = projects[slug]; if (!p || !modal || !modalContent) return; const shots = Array.from({ length: 8 }, (_, i) => `<div class="project-shot"><div class="project-shot-fallback"><i class="bi bi-image"></i></div><img src="assets/projects/${slug}/${i + 1}.PNG" alt="${p.title} screenshot ${i + 1}" loading="lazy" onerror="this.style.display='none'"></div>`).join(''); modalContent.innerHTML = `<div class="project-modal-head"><span>${p.category}</span><h2>${p.title}</h2><p>${p.description} The project is presented using its existing deployment folder and media structure while the public-facing identity has been upgraded for a corporate audience.</p></div><div class="project-gallery">${shots}</div>`; modal.classList.add('open'); modal.setAttribute('aria-hidden', 'false'); document.body.classList.add('modal-open') }
function closeProject() { if (!modal) return; modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true'); document.body.classList.remove('modal-open') } document.addEventListener('click', e => { const card = e.target.closest('[data-project]'); if (card) openProject(card.dataset.project); if (e.target.closest('[data-close-modal]')) closeProject() }); document.addEventListener('keydown', e => { if (e.key === 'Escape') closeProject(); if ((e.key === 'Enter' || e.key === ' ') && document.activeElement?.dataset?.project) { e.preventDefault(); openProject(document.activeElement.dataset.project) } });
